export const TEACHER_USER_ROLE = "TEACHER";
export const STUDENT_USER_ROLE = "STUDENT";
export const SUCCESS_CODE = "SUCCESS";
export const ERROR_CODE = "ERROR";
export enum STATUS_CODE {
  SUCCESS = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}
